config/routes.rb
Docket::Application.routes.draw do
  mount API::Docket => '/'

  resources :plans,            :only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :faculties,      :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :entrance_exams, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :sectors,        :only => [:index, :new, :create, :edit, :update, :destroy]
    get '/intakes/(:by_tuition)' => 'intakes#index', :constraints => { :by_tuition => Regexp.new(Intake.tuition.values.join('|')) }, :as => :scoped_intakes, :defaults => { :by_tuition => 'fulltime' }
    resources :streams,        :only => [:index, :new, :create, :edit, :update, :destroy] do
      resources :degrees,      :only => [] do
        resources :intakes,    :only => [:edit, :update, :destroy]
      end
    end
  end

  root :to => 'plans#index'
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  attr_accessible :abbr, :title, :departments_attributes

  belongs_to :plan

  has_many :departments, :dependent => :destroy

  accepts_nested_attributes_for :departments, :allow_destroy => true

  validates_presence_of :title, :abbr
  validates_uniqueness_of :title, :abbr, :scope => :plan_id
end

app/controllers/faculties_controller.rb
class FacultiesController < InheritedResources::Base
  actions :index, :new, :create, :edit, :update, :destroy
  belongs_to :plan

  has_scope :sorted_by_title, :default => 1 do |controller, scope|
    scope.order(:title)
  end
end

app/views/faculties/_department_fields.html.erb
  <%= f.input :abbr, :wrapper_html => { :class => 'min_width' } %>
  <%= f.input :title, :wrapper_html => { :class => 'max_width' } %>

  <%= f.link_to_remove 'удалить' %>

app/views/faculties/_form.html.erb
<%= simple_nested_form_for [@plan, @faculty] do |f| %>
  <%= f.input :abbr, :wrapper_html => { :class => 'min_width' } %>
  <%= f.input :title, :wrapper_html => { :class => 'max_width' } %>

  <%= f.fields_for :departments %>
  <%= f.link_to_add 'добавить кафедру', :departments %>

  <div class="actions">
    <%= f.submit 'Сохранить', :class => 'button' %>
    <%= link_to "Отмена", :back, :class => 'button' %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<%= content_for :title, "Редактирование факультета" %>
<%= render 'form' %>

app/views/faculties/index.html.erb
<%= content_for :title, "Список факультетов" %>

<% if @faculties.any? %>
  <div class='list'>
    <ul>
      <% @faculties.each do |faculty| %>
        <li>
          <span class='item'><%= faculty.title %></span>
          <div class="actions">
            <%= link_to 'редактировать', edit_plan_faculty_path(@plan, faculty) %>
            <%= link_to 'удалить', plan_faculty_path(@plan, faculty), :method => :delete, :confirm => 'Вы уверены?' %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div class="empty">Нет ни одного факультета</div>
<% end %>

<%= link_to "Добавить факультет", new_plan_faculty_path(@plan), :class => 'button' %>

app/views/faculties/new.html.erb
<%= content_for :title, "Добавление факультета" %>
<%= render 'form' %>