config/routes.rb
Docket::Application.routes.draw do
  mount API::Docket => '/'

  resources :plans,            :only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :faculties,      :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :entrance_exams, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :sectors,        :only => [:index, :new, :create, :edit, :update, :destroy]
    get '/intakes/(:by_tuition)' => 'intakes#index', :constraints => { :by_tuition => Regexp.new(Intake.tuition.values.join('|')) }, :as => :scoped_intakes, :defaults => { :by_tuition => 'fulltime' }
    resources :streams,        :only => [:index, :new, :create, :edit, :update, :destroy] do
      resources :degrees,      :only => [] do
        resources :intakes,    :only => [:edit, :update, :destroy]
      end
    end
  end

  root :to => 'plans#index'
end

app/models/sector.rb
class Sector < ActiveRecord::Base
  attr_accessible :title

  belongs_to :plan

  has_many :streams

  validates_presence_of :title
  validates_uniqueness_of :title, :scope => :plan_id
end

app/controllers/sectors_controller.rb
class SectorsController < InheritedResources::Base
  actions :index, :new, :create, :edit, :update, :destroy
  belongs_to :plan

  has_scope :sorted_by_title, :default => 1 do |controller, scope|
    scope.order(:title)
  end
end

app/views/sectors/_form.html.erb
<%= simple_form_for [@plan, @sector] do |f| %>
  <%= f.input :title, :wrapper_html => { :class => 'normal_width' } %>

  <div class="actions">
    <%= f.submit 'Сохранить', :class => 'button' %>
    <%= link_to "Отмена", :back, :class => 'button' %>
  </div>
<% end %>

app/views/sectors/edit.html.erb
<%= content_for :title, "Редактирование отрасли" %>
<%= render 'form' %>

app/views/sectors/index.html.erb
<%= content_for :title, "Список отраслей" %>

<% if @sectors.any? %>
  <div class='list'>
    <ul>
      <% @sectors.each do |sector| %>
        <li>
          <span class='item'><%= sector.title %></span>
          <div class="actions">
            <%= link_to 'редактировать', edit_plan_sector_path(@plan, sector) %>
            <%= link_to 'удалить', plan_sector_path(@plan, sector), :method => :delete, :confirm => 'Вы уверены?' %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div class="empty">Нет ни одной отрасли</div>
<% end %>

<%= link_to "Добавить отрасль", new_plan_sector_path(@plan), :class => 'button' %>

app/views/sectors/new.html.erb
<%= content_for :title, "Добавление отрасли" %>
<%= render 'form' %>