config/routes.rb
Docket::Application.routes.draw do
  mount API::Docket => '/'

  resources :plans,            :only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :faculties,      :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :entrance_exams, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :sectors,        :only => [:index, :new, :create, :edit, :update, :destroy]
    get '/intakes/(:by_tuition)' => 'intakes#index', :constraints => { :by_tuition => Regexp.new(Intake.tuition.values.join('|')) }, :as => :scoped_intakes, :defaults => { :by_tuition => 'fulltime' }
    resources :streams,        :only => [:index, :new, :create, :edit, :update, :destroy] do
      resources :degrees,      :only => [] do
        resources :intakes,    :only => [:edit, :update, :destroy]
      end
    end
  end

  root :to => 'plans#index'
end

app/models/stream.rb
class Stream < ActiveRecord::Base

  attr_accessible :code, :title, :sector_id, :degrees_attributes

  belongs_to :sector
  belongs_to :plan
  has_many :degrees, :dependent => :destroy
  has_many :intakes, :through => :degrees

  accepts_nested_attributes_for :degrees, :allow_destroy => true

  delegate :title, :to => :sector, :prefix => true, :allow_nil => true
  delegate :year, :to => :plan, :prefix => true

  validates_presence_of :code, :title, :sector_id
  validates_uniqueness_of :code, :scope => [:plan_id]

  after_save :check_intakes

  def to_s
    "".tap do |string|
      string << code
      string << "&nbsp;&mdash;&nbsp;"
      string << title
    end.html_safe
  end

  private
    def check_intakes
      degrees.each do |degree|
        old_tuitions = degree.intakes.pluck(:tuition) || []
        new_tuitions = degree.tuitions.try(:delete_if, &:blank?) || []

        next if old_tuitions == new_tuitions

        if (delta = old_tuitions - new_tuitions).any?
          degree.intakes.where(:tuition => delta).destroy_all
        end

        if (delta = new_tuitions - old_tuitions).any?
          delta.each do |tuition|
            intake = degree.intakes.new :tuition => tuition
            intake.save(:validate => false)
          end
        end
      end
    end
end

app/controllers/streams_controller.rb
class StreamsController < InheritedResources::Base
  actions :index, :new, :create, :edit, :update, :destroy
  belongs_to :plan

  has_scope :sorted_by_code, :default => 1 do |controller, scope|
    scope.order(:code)
  end
end

app/views/streams/_degree_fields.html.erb
  <%= f.input :code, :include_blank => '- не выбрано -', :wrapper_html => { :class => 'normal_width' } %>
  <%= f.input :tuitions, :as => :check_boxes, :collection => Intake.tuition.options %>
  <%= f.association :entrance_exams, :as => :check_boxes, :collection => @plan.entrance_exams %>

  <%= f.link_to_remove 'удалить' %>

app/views/streams/_form.html.erb
<%= simple_nested_form_for [@plan, @stream] do |f| %>
  <%= f.input :code, :wrapper_html => { :class => 'min_width' } %>
  <%= f.input :title, :wrapper_html => { :class => 'max_width' } %>
  <%= f.association :sector, :collection => @plan.sectors, :include_blank => '- не выбрано -', :wrapper_html => { :class => 'normal_width' } %>

  <%= f.fields_for :degrees %>
  <%= f.link_to_add 'добавить квалификацию', :degrees %>

  <div class="actions">
    <%= f.submit 'Сохранить', :class => 'button' %>
    <%= link_to "Отмена", :back, :class => 'button' %>
  </div>
<% end %>

app/views/streams/_stream.html.erb
<tr>
  <td rowspan=<%= stream.degrees.count+1+stream.degrees.flat_map(&:intakes).count %>><%= stream.code %></td>
  <td rowspan=<%= stream.degrees.count+1+stream.degrees.flat_map(&:intakes).count %>>
    <%= stream.title %>
    <%= link_to "редактировать", edit_plan_stream_path(@plan, stream) %>
    <%= link_to "удалить", plan_stream_path(@plan, stream), :method => :delete, :confirm => 'Вы уверены?' %>
  </td>
  <td rowspan=<%= stream.degrees.count+1+stream.degrees.flat_map(&:intakes).count %>><%= stream.sector_title %></td>
</tr>
<% stream.degrees.order(:code).each do |degree| %>
  <tr>
    <td rowspan=<%= degree.intakes.count+1 %>><%= "#{stream.code}.#{degree.code}" %></td>
    <td rowspan=<%= degree.intakes.count+1 %>>
      <%= degree.code_text %>
    </td>
    <td rowspan=<%= degree.intakes.count+1 %>><%= degree.entrance_exams.map(&:title).join(', ') %></td>
  </tr>
  <% degree.intakes.order(:tuition).each do |intake| %>
    <tr>
      <td><%= intake.tuition_text %> </td>
    </tr>
  <% end %>
<% end %>

app/views/streams/edit.html.erb
<%= content_for :title, "Редактирование направления" %>
<%= render 'form' %>

app/views/streams/index.html.erb
<%= link_to 'Добавить направление', new_plan_stream_path(@plan), :class => 'button' %>

<% if @streams.any? %>
  <div class="list">
    <table>
      <thead>
        <tr>
          <th><%= Stream.human_attribute_name(:code) %></th>
          <th><%= Stream.human_attribute_name(:title) %></th>
          <th><%= Stream.human_attribute_name(:sector) %></th>
          <th><%= Degree.human_attribute_name(:code) %></th>
          <th><%= Degree.human_attribute_name(:title) %></th>
          <th><%= Degree.human_attribute_name(:entrance_exams) %></th>
          <th><%= Intake.human_attribute_name(:tuition) %></th>
        </tr>
      </thead>
      <tbody>
        <%= render @streams.order(:code) %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="empty">Нет ни одного направления подготовки</div>
<% end %>

app/views/streams/new.html.erb
<%= content_for :title, "Добавление направления" %>
<%= render 'form' %>