config/routes.rb
Docket::Application.routes.draw do
  mount API::Docket => '/'

  resources :plans,            :only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :faculties,      :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :entrance_exams, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :sectors,        :only => [:index, :new, :create, :edit, :update, :destroy]
    get '/intakes/(:by_tuition)' => 'intakes#index', :constraints => { :by_tuition => Regexp.new(Intake.tuition.values.join('|')) }, :as => :scoped_intakes, :defaults => { :by_tuition => 'fulltime' }
    resources :streams,        :only => [:index, :new, :create, :edit, :update, :destroy] do
      resources :degrees,      :only => [] do
        resources :intakes,    :only => [:edit, :update, :destroy]
      end
    end
  end

  root :to => 'plans#index'
end

app/models/entrance_exam.rb
class EntranceExam < ActiveRecord::Base
  attr_accessible :title

  belongs_to :plan

  has_and_belongs_to_many :degrees

  validates_presence_of :title
  validates_uniqueness_of :title, :scope => :plan_id
end

app/controllers/entrance_exams_controller.rb
class EntranceExamsController < InheritedResources::Base
  actions :index, :new, :create, :edit, :update, :destroy
  belongs_to :plan

  has_scope :sorted_by_title, :default => 1 do |controller, scope|
    scope.order(:title)
  end
end

app/views/entrance_exams/_form.html.erb
<%= simple_form_for [@plan, @entrance_exam] do |f| %>
  <%= f.input :title, :wrapper_html => { :class => 'normal_width' } %>

  <div class="actions">
    <%= f.submit 'Сохранить', :class => 'button' %>
    <%= link_to "Отмена", :back, :class => 'button' %>
  </div>
<% end %>

app/views/entrance_exams/edit.html.erb
<%= content_for :title, "Редактирование экзамена" %>
<%= render 'form' %>

app/views/entrance_exams/index.html.erb
<%= content_for :title, "Список вступительных испытаний" %>

<% if @entrance_exams.any? %>
  <div class='list'>
    <ul>
      <% @entrance_exams.each do |entrance_exam| %>
        <li>
          <span class='item'><%= entrance_exam.title %></span>
          <div class="actions">
            <%= link_to 'редактировать', edit_plan_entrance_exam_path(@plan, entrance_exam) %>
            <%= link_to 'удалить', plan_entrance_exam_path(@plan, entrance_exam), :method => :delete, :confirm => 'Вы уверены?' %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div class="empty">Нет ни одного вступительного испытания</div>
<% end %>

<%= link_to "Добавить вступительное испытание", new_plan_entrance_exam_path(@plan), :class => 'button' %>

app/views/entrance_exams/new.html.erb
<%= content_for :title, "Добавление экзамена" %>
<%= render 'form' %>